namespace MSFSBlindAssist.Aircraft.A300;

// The spoken names and position words of the A300's panel rows. Hand-chosen: iniBuilds' tooltip
// titles repeat across families ("BATTERY" x3) and a few are wrong ("ALTITUDE KNOB" on the vertical
// speed knob, "CPT BAROMETER" on the first officer's). Keyed by input event id without AIRLINER_.
public static partial class A300PanelLayout
{
    /// <summary>Input event id (without <c>AIRLINER_</c>) to spoken name. A control not listed here is
    /// named by <see cref="AudioName"/> or from its tooltip title through <see cref="SpokenWord"/>.</summary>
    private static readonly Dictionary<string, string> NameOverrides = new(StringComparer.Ordinal)
    {
        ["AUTO_PRESS_SELECT"] = "Auto pressure limit",
        ["PRESS_OUTFLOW_FWD"] = "Forward outflow valve",
        ["PRESS_OUTFLOW_AFT"] = "Aft outflow valve",
        ["AUTO_PRESS_1"] = "Cabin regulator 1",
        ["AUTO_PRESS_2"] = "Cabin regulator 2",
        ["PRESS_SYS_1"] = "Pressurization system 1",
        ["PRESS_SYS_2"] = "Pressurization system 2",
        ["MAN_PRESS"] = "Manual pressurization",
        ["VS_CTRLSWITCH"] = "Manual vertical speed control",
        ["NAVATTLEFT"] = "IRS 1 mode",
        ["NAVATTRIGHT"] = "IRS 2 mode",
        ["NAVATTCTR"] = "IRS 3 mode",
        ["IRS_MODE_SELECT"] = "IRS display selector",
        ["IRS_SYS_DYSPL"] = "IRS system display",
        ["APU_MASTERSWITCH"] = "APU master switch",
        ["APU_START"] = "APU start",
        ["APU_FUEL_PMP"] = "APU fuel pump",
        ["ANTI_ICE_E1"] = "Engine 1 anti-ice",
        ["ANTI_ICE_E2"] = "Engine 2 anti-ice",
        ["WING_SUPPLY"] = "Wing anti-ice supply",
        ["WING_MODE"] = "Wing anti-ice supply mode",
        ["CPT_WIPER_KNOB"] = "Left wiper",
        ["FO_WIPER_KNOB"] = "Right wiper",
        ["WINDOW_HEAT_1"] = "Window heat, lateral",
        ["WINDOW_HEAT_2"] = "Window heat, windshield and lateral",
        ["CAPT_HEAT"] = "Captain probe heat",
        ["STBY_HEAT"] = "Standby probe heat",
        ["FO_HEAT"] = "First officer probe heat",
        ["AIR_XFEED"] = "Crossbleed",
        ["AIR_XFEED_AUTO"] = "Crossbleed mode",
        ["ENG1_HP_VALVE"] = "Engine 1 HP valve",
        ["ENG2_HP_VALVE"] = "Engine 2 HP valve",
        ["ENG1_WING_BLEED_VALVE"] = "Engine 1 bleed",
        ["ENG2_WING_BLEED_VALVE"] = "Engine 2 bleed",
        ["ECON_FLOW"] = "Economy flow",
        ["PACK1_MODE"] = "Pack 1 mode",
        ["PACK2_MODE"] = "Pack 2 mode",
        ["PACK1_MAN"] = "Pack 1 manual temperature",
        ["PACK2_MAN"] = "Pack 2 manual temperature",
        ["PACK_1_VALVE"] = "Pack 1 valve",
        ["PACK_2_VALVE"] = "Pack 2 valve",
        ["ISO_VALVE_RIGHT"] = "Right isolation valve",
        ["ISO_VALVE_LEFT"] = "Left isolation valve",
        ["COCKPITTEMP_KNOB"] = "Cockpit temperature",
        ["TEMP_SELECT"] = "Temperature indication selector",
        ["FWD_CABIN_TEMP"] = "Forward cabin temperature",
        ["MID_CABIN_TEMP"] = "Mid cabin temperature",
        ["AFT_CABIN_TEMP"] = "Aft cabin temperature",
        ["BULK_CARGO_TEMP"] = "Bulk cargo temperature",
        ["BULK_CARGO_TEMP_PAX"] = "Bulk cargo temperature, passenger version",
        ["APU_BLEEDSWITCH"] = "APU bleed",
        ["CREW_O2_SUPPLY"] = "Crew low pressure supply",
        ["COURIER_O2_SUPPLY"] = "Courier low pressure supply",
        ["PAX_OXY_SUPPLY"] = "Crew oxygen supply",   // iniBuilds' title; it toggles the courier supply's variable
        ["AC_BUS_SELECT"] = "AC indication selector",
        ["DC_BUS_SELECT"] = "DC indication selector",
        ["IDG1_PUSH"] = "IDG 1 disconnect",
        ["IDG2_PUSH"] = "IDG 2 disconnect",
        ["BAT_OVRD"] = "Battery override",
        ["STBY_GEN"] = "Standby generator",
        ["OVR_SUP_1"] = "Override supply 1",
        ["OVR_SUP_2"] = "Override supply 2",
        ["APU_GEN"] = "APU generator",
        ["BATT_1"] = "Battery 1",
        ["BATT_2"] = "Battery 2",
        ["BATT_3"] = "Battery 3",
        ["GEN_1"] = "Engine 1 generator",
        ["GEN_2"] = "Engine 2 generator",
        ["GALLEY"] = "Galley",
        ["SPLR_7"] = "Spoiler 7",
        ["SPLR_6"] = "Spoiler 6",
        ["SPLR_5"] = "Spoiler 5",
        ["SPLR_41"] = "Spoilers 4 and 1",
        ["SPLR_32"] = "Spoilers 3 and 2",
        ["PITCHSYS_1"] = "Pitch feel system 1",
        ["PITCHSYS_2"] = "Pitch feel system 2",
        ["RUDTVLSYS_1"] = "Rudder travel limiter system 1",
        ["RUDTVLSYS_2"] = "Rudder travel limiter system 2",
        ["OVBD_VALVE"] = "Overboard valve",
        ["MAIN_DECK_VALVE"] = "Main deck cargo valve",
        ["EQPT_COOL_EXTR"] = "Extract valve",
        ["GND_COOL_OVRD"] = "Ground cooling override",
        ["GND_COOL_CTL"] = "Ground cooling control",
        ["COCKPIT_LOCK_SWITCH"] = "Cockpit door lock",
        ["COCKPIT_DOOR"] = "Cockpit door",
        ["FLTRCDR_GNDCTL"] = "Flight recorder ground control",
        ["CVR_TEST"] = "CVR test",
        ["FUEL_ISO_1"] = "Fuel isolation valve 1",
        ["FUEL_ISO_2"] = "Fuel isolation valve 2",
        ["FUEL_ISO_3"] = "Fuel isolation valve 3",
        ["FUEL_ISO_4"] = "Fuel isolation valve 4",
        ["FUEL_XFEED"] = "Fuel crossfeed",
        ["AUX_AUTO"] = "Additional center tank feed mode",
        ["OUT_TK_PMP_L1"] = "Left outer tank pump 1",
        ["OUT_TK_PMP_L2"] = "Left outer tank pump 2",
        ["OUT_TK_PMP_R1"] = "Right outer tank pump 1",
        ["OUT_TK_PMP_R2"] = "Right outer tank pump 2",
        ["INR_TK_PMP_L1"] = "Left inner tank pump 1",
        ["INR_TK_PMP_L2"] = "Left inner tank pump 2",
        ["INR_TK_PMP_R1"] = "Right inner tank pump 1",
        ["INR_TK_PMP_R2"] = "Right inner tank pump 2",
        ["CTR_TK_PMP_L"] = "Left center tank pump",
        ["CTR_TK_PMP_R"] = "Right center tank pump",
        ["TRMTK_1_PMP"] = "Left trim tank pump",
        ["TRMTK_2_PMP"] = "Right trim tank pump",
        ["FUEL_MODE"] = "Trim tank feed mode",
        ["TRMTK_ISO"] = "Trim tank isolation valve",
        ["SERVOCTL_B"] = "Blue servo control",
        ["SERVOCTL_G"] = "Green servo control",
        ["SERVOCTL_Y"] = "Yellow servo control",
        ["HYDPUMP_B_E1"] = "Engine 1 blue pump",
        ["HYDPUMP_G_E1"] = "Engine 1 green pump",
        ["HYDPUMP_G_E2"] = "Engine 2 green pump",
        ["HYDPUMP_Y_E2"] = "Engine 2 yellow pump",
        ["HYDPWRPTU_B"] = "Blue PTU",
        ["HYDPWRPTU_Y"] = "Yellow PTU",
        ["HYDPWRPUMP_G"] = "Green electric pump",
        ["ENG_TRIM"] = "Engine trim",
        ["ENG_1_EPR"] = "Engine 1 N1 mode",
        ["ENG_2_EPR"] = "Engine 2 N1 mode",
        ["ENG_1_START"] = "Engine 1 starter",
        ["ENG_2_START"] = "Engine 2 starter",
        ["IGNITION_KNOB"] = "Ignition",
        ["FIRE_1_AG1"] = "Engine 1 agent 1",
        ["FIRE_1_AG2"] = "Engine 1 agent 2",
        ["FIRE_1_LOOP_A"] = "Engine 1 loop A",
        ["FIRE_1_LOOP_B"] = "Engine 1 loop B",
        ["ENG1_FIRE_PUSH1"] = "Engine 1 squib test",
        ["ENG1_FIRE_PUSH2"] = "Engine 1 loop test",
        ["ENG1_FIRE_LATCH"] = "Engine 1 fire handle latch",
        ["FIRE_HANDLE_ENG1"] = "Engine 1 fire handle",
        ["FIRE_2_AG1"] = "Engine 2 agent 1",
        ["FIRE_2_AG2"] = "Engine 2 agent 2",
        ["FIRE_2_LOOP_A"] = "Engine 2 loop A",
        ["FIRE_2_LOOP_B"] = "Engine 2 loop B",
        ["ENG2_FIRE_PUSH1"] = "Engine 2 squib test",
        ["ENG2_FIRE_PUSH2"] = "Engine 2 loop test",
        ["ENG2_FIRE_LATCH"] = "Engine 2 fire handle latch",
        ["FIRE_HANDLE_ENG2"] = "Engine 2 fire handle",
        ["FIRE_APU_AG"] = "APU agent",
        ["FIRE_APU_LOOP_A"] = "APU loop A",
        ["FIRE_APU_LOOP_B"] = "APU loop B",
        ["APU_FIRE_PUSH1"] = "APU squib test",
        ["APU_FIRE_PUSH2"] = "APU loop test",
        ["ENG_APU_FIRE_LATCH"] = "APU fire handle latch",
        ["FIRE_HANDLE_APU"] = "APU fire handle",
        ["SMOKE_MID1_1"] = "Main deck smoke detector mid 1 left",
        ["SMOKE_MID1_2"] = "Main deck smoke detector mid 1 right",
        ["SMOKE_MID2_1"] = "Main deck smoke detector mid 2 left",
        ["SMOKE_MID2_2"] = "Main deck smoke detector mid 2 right",
        ["SMOKE_AFT_1"] = "Main deck smoke detector aft left",
        ["SMOKE_AFT_2"] = "Main deck smoke detector aft right",
        ["CARGO_FWD_SMOKE_TOGGLE"] = "Forward cargo smoke agent",
        ["CARGO_FWD_SMOKE_TOGGLE_GUARD"] = "Forward cargo smoke agent guard",
        ["CARGO_AFT_SMOKE_TOGGLE"] = "Aft cargo smoke agent",
        ["CARGO_AFT_SMOKE_TOGGLE_GUARD"] = "Aft cargo smoke agent guard",
        ["SMOKE_TEST"] = "Smoke test",
        ["PITCH_TRIM_1"] = "Pitch trim 1",
        ["PITCH_TRIM_2"] = "Pitch trim 2",
        ["YAW_DAMPER_1"] = "Yaw damper 1",
        ["YAW_DAMPER_2"] = "Yaw damper 2",
        ["ATS_1"] = "Autothrottle 1",
        ["ATS_2"] = "Autothrottle 2",
        ["STORMLIGHT"] = "Storm light",
        ["DOMELIGHT"] = "Dome light",
        ["REAR_DOME_SWITCH"] = "Rear dome light switch",
        ["BRIGHTLIGHT"] = "Dome light brightness",
        ["STROBESWITCH"] = "Strobe lights",
        ["BEACONSWITCH"] = "Beacon",
        ["RWY_TOFF_L"] = "Left runway turnoff light",
        ["RWY_TOFF_R"] = "Right runway turnoff light",
        ["LANDINGLEFTSWITCH"] = "Left landing light",
        ["LANDINGRIGHTSWITCH"] = "Right landing light",
        ["WINGLIGHTSWITCH"] = "Wing lights",
        ["NAVLIGHT_SWITCH"] = "Navigation and logo lights",
        ["NOSELIGHTSWITCH"] = "Nose light",
        ["SEATBELT"] = "Seat belt signs",
        ["NOSMOKING"] = "No smoking signs",
        ["EMERGEXIT_SWITCH"] = "Emergency exit lights",
        ["ANN_LIGHTSWITCH"] = "Annunciator lights",
        ["REAR_READLIGHT_KNOB"] = "Rear reading light",
        ["READLIGHT_KNOB"] = "Reading light",
        ["STBYCOMPASSSWITCH"] = "Standby compass light",
        ["COMPASS_COVER"] = "Standby compass",
        ["SPEED_KNOB_PUSH"] = "Speed knob push",
        ["SPEED_KNOB_PULL"] = "Speed knob pull",
        ["SPEED_KNOB"] = "Speed knob",
        ["HEADING_KNOB_PUSH"] = "Heading knob push",
        ["HEADING_KNOB_PULL"] = "Heading knob pull",
        ["HEADING_KNOB"] = "Heading knob",
        ["ALT_KNOB_PUSH"] = "Altitude knob push",
        ["ALT_KNOB_PULL"] = "Altitude knob pull",
        ["ALT_KNOB"] = "Altitude knob",
        ["VS_KNOB_PUSH"] = "Vertical speed knob push",
        ["VS_KNOB_PULL"] = "Vertical speed knob pull",
        ["VS_KNOB"] = "Vertical speed knob",
        ["BANK_KNOB"] = "Bank limit",
        ["ATHR_BUTTON"] = "Autothrottle",
        ["SPDMACH"] = "Speed Mach",
        ["ALTHLD_BUTTON"] = "Altitude hold",
        ["LVLCH_BUTTON"] = "Level change",
        ["PROFILE_BUTTON"] = "Profile",
        ["HDGSEL_BUTTON"] = "Heading select",
        ["NAV_BUTTON"] = "NAV",
        ["VL_BUTTON"] = "VOR LOC",
        ["LAND_BUTTON"] = "Land",
        ["AP_SWITCH_1"] = "Autopilot 1",
        ["AP_SWITCH_2"] = "Autopilot 2",
        ["CWS_PUSH"] = "CWS",
        ["MCU_LIGHT_KNOB"] = "FCU lighting",
        ["ATC_CPT"] = "ATC message",
        ["ATC_FO"] = "ATC message",
        ["AUTOLAND_CPT"] = "Autoland light",
        ["AUTOLAND_FO"] = "Autoland light",
        ["STOP_CAPT"] = "Stop rudder input",
        ["STOP_FO"] = "Stop rudder input",
        ["CPT_PFD_BRT"] = "PFD brightness",
        ["FO_PFD_BRT"] = "PFD brightness",
        ["CPT_ND_BRT"] = "Weather radar brightness",
        ["FO_ND_BRT"] = "Weather radar brightness",
        ["CPT_ECAM_BRT"] = "ND brightness",
        ["FO_ECAM_BRT"] = "ND brightness",
        ["CPT_FLT_DIR"] = "Flight director",
        ["FO_FLT_DIR"] = "Flight director",
        ["CPT_VOR"] = "Navigation source",
        ["FO_VOR"] = "Navigation source",
        ["CAPT_DH_SET"] = "Decision height knob",
        ["FO_DH_SET"] = "Decision height knob",
        ["DH_CPT"] = "Decision height push",
        ["FO_DH"] = "Decision height push",
        ["CPT_FPA"] = "FPA",
        ["FO_FPA"] = "FPA",
        ["EFIS_MODE_CPT"] = "ND mode",
        ["EFIS_MODE_FO"] = "ND mode",
        ["EFIS_RANGE_CPT"] = "ND range",
        ["EFIS_RANGE_FO"] = "ND range",
        ["EFIS_CSTR_CPT"] = "Constraints",
        ["EFIS_FO_CSTR"] = "Constraints",
        ["EFIS_WPT_CPT"] = "Waypoints",
        ["EFIS_FO_WPT"] = "Waypoints",
        ["EFIS_VOR_CPT"] = "VORs",
        ["EFIS_FO_VOR"] = "VORs",
        ["EFIS_NDB_CPT"] = "NDBs",
        ["EFIS_FO_NDB"] = "NDBs",
        ["EFIS_ARPT_CPT"] = "Airports",
        ["EFIS_FO_ARPT"] = "Airports",
        ["TOGA_SEL"] = "TOGA",
        // Rows from both sides that share a system panel (Warnings, Clock, Source Switching, GPWS) say
        // their side first ([VAR-1]); rows on each side's own panel do not.
        ["TERR_CPT"] = "Captain terrain on ND",
        ["TERR_FO"] = "First officer terrain on ND",
        ["CPT_ALTIMETER_KNOB_PUSH"] = "Altimeter knob push",
        ["FO_ALTIMETER_KNOB_PUSH"] = "Altimeter knob push",
        ["CPT_ALTIMETER_KNOB_PULL"] = "Altimeter knob pull",
        ["FO_ALTIMETER_KNOB_PULL"] = "Altimeter knob pull",
        ["CPT_ALTIMETER_KNOB"] = "Altimeter knob",
        ["FO_ALTIMETER_KNOB"] = "Altimeter knob",
        ["CPT_ALTI_BUG_SET"] = "Altimeter altitude bug",
        ["FO_ALTI_BUG_SET"] = "Altimeter altitude bug",
        ["CPT_CLOCK_DATE"] = "Captain clock date",
        ["FO_CLOCK_DATE"] = "First officer clock date",
        ["CPT_CLOCK_MODE"] = "Captain clock mode",
        ["FO_CLOCK_MODE"] = "First officer clock mode",
        ["CPT_CLOCK_START"] = "Captain chrono",
        ["FO_CLOCK_START"] = "First officer chrono",
        ["CPT_CLOCK_RUN"] = "Captain elapsed time",
        ["FO_CLOCK_RUN"] = "First officer elapsed time",
        ["GPWS_CPT"] = "Captain GPWS test",
        ["GPWS_FO"] = "First officer GPWS test",
        ["MASTER_WARNING_CPT"] = "Captain master warning",
        ["MASTER_WARNING_FO"] = "First officer master warning",
        ["MASTER_CAUTION_CPT"] = "Captain master caution",
        ["MASTER_CAUTION_FO"] = "First officer master caution",
        ["CPT_ATT_HDG"] = "Captain attitude and heading to IRS 3",
        ["FO_SW_ATT"] = "First officer attitude and heading to IRS 3",
        ["CPT_ADC_INST"] = "Captain air data to system 2",
        ["FO_SW_ADC"] = "First officer air data to system 2",
        ["CPT_FD_PUSH"] = "Captain flight director to system 2",
        ["FO_SW_FD"] = "First officer flight director to system 2",
        ["CPT_EFIS_SGU"] = "Captain EFIS to SGU 3",
        ["FO_SW_EFIS"] = "First officer EFIS to SGU 3",
        ["CPT_PFD_XFR"] = "Captain PFD and ND transfer",
        ["FO_PFD_XFR"] = "First officer PFD and ND transfer",
        ["CPT_TERR_MODE"] = "Captain terrain mode",
        ["FO_TERR_MODE"] = "First officer terrain mode",
        ["GPWS_FLAP_SWITCH"] = "GPWS flap override",
        ["CPT_MAP_LIGHT"] = "Map light",
        ["FO_MAP_LIGHT"] = "Map light",
        ["CPT_MIP_LIGHT"] = "Panel lighting",
        ["FO_MIP_LIGHT"] = "Panel lighting",
        ["CPT_MIP_SPILL"] = "Panel flood light",
        ["CPT_CONSOLE_SWITCH"] = "Console flood light",
        ["FO_CONSOLE_SWITCH"] = "Console flood light",
        ["OXY_CAPT_TEST"] = "Oxygen test",
        ["OXY_FO_TEST"] = "Oxygen test",
        ["CPT_OXY_PUSH"] = "Oxygen mask test",
        ["FO_OXY_PUSH"] = "Oxygen mask test",
        ["STBY_ALTIMETER_KNOB"] = "Standby altimeter knob",
        ["ADI_CAGE"] = "Standby horizon cage",
        ["ANTI_SKID"] = "Brake system",
        ["AUTO_BRK_LO"] = "Autobrake low",
        ["AUTO_BRK_MID"] = "Autobrake medium",
        ["AUTO_BRK_MAX"] = "Autobrake max",
        ["FLEX_TEMP"] = "Flex temperature knob",
        ["TRP_TOGA"] = "TRP takeoff go-around",
        ["TRP_MCT"] = "TRP max continuous",
        ["TRP_CL"] = "TRP climb",
        ["TRP_CR"] = "TRP cruise",
        ["TRP_AUTO"] = "TRP auto",
        ["TRP_FLEXTO"] = "TRP flex takeoff",
        ["LANDING_ELEV_SET"] = "Landing elevation knob",
        ["LDG_TEST"] = "Landing gear warning test",
        ["LDG_POS_DET"] = "Gear position detection system",
        ["BRAKE_FAN"] = "Brake fans",
        ["GEAR_LEVER"] = "Gear lever",
        ["ENG1_CUTOFF"] = "Engine 1 fuel lever",
        ["ENG2_CUTOFF"] = "Engine 2 fuel lever",
        ["AT_DISCO1"] = "Autothrottle disconnect",
        ["PARKINGBRAKE"] = "Parking brake",
        ["PARKBRAKE_PRESS_PUSH"] = "Brake accumulator charge",
        ["NORM_CANCEL"] = "Normal cancel",
        ["EMER_CANCEL_BUTTON"] = "Emergency cancel",
        ["TO_CONFIG_TEST"] = "Takeoff config test",
        ["GPWS_FLAPS_CONFIG"] = "GPWS landing flaps",
        ["BRIGHTNESS_KNOB_1"] = "Captain MCDU brightness",
        ["BRIGHTNESS_KNOB_2"] = "First officer MCDU brightness",
        ["VOR_CRS_CAPT_PUSH"] = "VOR 1 course push",
        ["VOR_CRS_CAPT"] = "VOR 1 course",
        ["VOR100_CAPT"] = "VOR 1 megahertz",
        ["VOR10_CAPT"] = "VOR 1 kilohertz",
        ["ILS_CRS"] = "ILS course",
        ["ILS_100"] = "ILS megahertz",
        ["ILS_10"] = "ILS kilohertz",
        ["VOR_CRS_FO_PUSH"] = "VOR 2 course push",
        ["VOR_CRS_FO"] = "VOR 2 course",
        ["VOR100_FO"] = "VOR 2 megahertz",
        ["VOR10_FO"] = "VOR 2 kilohertz",
        ["IDC_BRT_CPT"] = "Captain IDC brightness",
        ["IDC_BRT_FO"] = "First officer IDC brightness",
        ["WER_MODE"] = "Weather radar mode",
        ["WER_GAIN"] = "Weather radar gain",
        ["WER_SYS"] = "Weather radar system",
        ["WER_TILT"] = "Weather radar tilt",
        ["PEDESTAL_LIGHT_KNOB"] = "Pedestal lighting",
        ["OVERHEAD_LIGHT_KNOB"] = "Overhead panel lighting",
        ["CPT_RADIO_VOXIDENT"] = "Voice ident filter",
        ["FO_RADIO_VOXIDENT"] = "Voice ident filter",
        ["CPT_VHF1_MHZ"] = "VHF 1 megahertz",
        ["CPT_VHF1_KHZ"] = "VHF 1 kilohertz",
        ["CPT_VHF2_MHZ"] = "VHF 1 standby megahertz",
        ["CPT_VHF2_KHZ"] = "VHF 1 standby kilohertz",
        ["FO_VHF1_MHZ"] = "VHF 2 megahertz",
        ["FO_VHF1_KHZ"] = "VHF 2 kilohertz",
        ["FO_VHF2_MHZ"] = "VHF 2 standby megahertz",
        ["FO_VHF2_KHZ"] = "VHF 2 standby kilohertz",
        ["CPT_VHF_TFR"] = "VHF 1 transfer",
        ["CPT_VHF_SQL"] = "VHF 1 squelch",
        ["FO_VHF_TFR"] = "VHF 2 transfer",
        ["FO_VHF_SQL"] = "VHF 2 squelch",
        ["TCAS_MODE"] = "Transponder mode",
        ["TCAS_BIG"] = "Transponder code large knob",
        ["TCAS_SMALL"] = "Transponder code small knob",
        ["TCAS_ABV"] = "TCAS above below",
        ["TCAS_ALT"] = "Altitude reporting",
        ["XPDR_SWITCH"] = "Transponder system",
        ["TCAS_TEST"] = "TCAS test",
        ["TCAS_IDENT"] = "Ident",
        ["TCAS_RANGE"] = "TCAS range",
        ["CPT_ADF1_BIG"] = "ADF 1 hundreds",
        ["CPT_ADF1_MED"] = "ADF 1 tens",
        ["CPT_ADF1_SMALL"] = "ADF 1 units",
        ["CPT_ADF2_BIG"] = "ADF 1 standby hundreds",
        ["CPT_ADF2_MED"] = "ADF 1 standby tens",
        ["CPT_ADF2_SMALL"] = "ADF 1 standby units",
        ["ADF1_TFR"] = "ADF 1 transfer",
        ["ADF1_ANT"] = "ADF 1 mode",
        ["ADF1_TONE"] = "ADF 1 tone",
        ["FO_ADF1_BIG"] = "ADF 2 hundreds",
        ["FO_ADF1_MED"] = "ADF 2 tens",
        ["FO_ADF1_SMALL"] = "ADF 2 units",
        ["FO_ADF2_BIG"] = "ADF 2 standby hundreds",
        ["FO_ADF2_MED"] = "ADF 2 standby tens",
        ["FO_ADF2_SMALL"] = "ADF 2 standby units",
        ["ADF2_TFR"] = "ADF 2 transfer",
        ["ADF2_ANT"] = "ADF 2 mode",
        ["ADF2_TONE"] = "ADF 2 tone",
        ["ECAM_L_BRT"] = "Left ECAM brightness",
        ["ECAM_R_BRT"] = "Right ECAM brightness",
        ["SGU_1"] = "SGU 1",
        ["SGU_2"] = "SGU 2",
        ["ECAM_ENG"] = "Engine page",
        ["ECAM_HYD"] = "Hydraulic page",
        ["ECAM_AC"] = "AC electrical page",
        ["ECAM_DC"] = "DC electrical page",
        ["ECAM_BLEED"] = "Bleed page",
        ["ECAM_COND"] = "Air conditioning page",
        ["ECAM_PRESS"] = "Pressurization page",
        ["ECAM_FUEL"] = "Fuel page",
        ["ECAM_APU"] = "APU page",
        ["ECAM_FCTL"] = "Flight controls page",
        ["ECAM_DOOR"] = "Doors page",
        ["ECAM_WHEEL"] = "Wheels page",
        ["ECAM_CLR"] = "Clear",
        ["ECAM_RCL"] = "Recall",
        ["ECAM_STS"] = "Status page",
        ["AILERONTRIM_1"] = "Aileron trim switch 1",
        ["AILERONTRIM_2"] = "Aileron trim switch 2",
        ["NOSE_TRIM"] = "Rudder trim",
        ["TRIM_KORRY"] = "Rudder trim reset",
        ["MAN_GEAR_HANDLE_EXT"] = "Gear gravity extension handle",
        ["CPT_YOKE_TRIM"] = "Captain pitch trim switch",
        ["FO_YOKE_TRIM"] = "First officer pitch trim switch",
        ["CPT_AP_DISCO"] = "Captain autopilot disconnect",
        ["FO_AP_DISCO"] = "First officer autopilot disconnect",
        ["CPT_YOKE_LIGHT_KNOB"] = "Captain yoke light",
        ["FO_YOKE_LIGHT_KNOB"] = "First officer yoke light",
        ["RAT_CAPT"] = "Ram air turbine deploy",
        ["POINTER_RESET"] = "Maximum pointer reset",
        ["CB_TCAS"] = "TCAS circuit breaker",
        ["A300_MAIN_CARGO_DOOR_145"] = "Cargo door 145 degrees",
        ["A300_MAIN_CARGO_DOOR_70"] = "Cargo door 70 degrees",
        ["MAIN_CARGO_DOOR_LIGHT_CARGO"] = "Cargo compartment light",
        ["MAIN_CARGO_DOOR_LIGHT_ENTRY"] = "Cargo entry light",
        ["MAIN_CARGO_DOOR_LIGHT_LOADER"] = "Loader tarmac light",
    };

    /// <summary>A position another clickspot reaches: the gravity extension handle's own event only pulls it
    /// (INI_GRAVITY_HANDLE_CMD), and iniBuilds stows it with a separate clickspot that clears it (measured
    /// 2026-10-10: picking Stowed through its own event stayed Extended). Control id → position → event.</summary>
    private static readonly Dictionary<string, Dictionary<double, string>> PositionEvents = new(StringComparer.Ordinal)
    {
        ["MAN_GEAR_HANDLE_EXT"] = new() { [0] = "AIRLINER_Man_Gear_Handle_Hide_Set" },
    };

    /// <summary>The event that reaches <paramref name="position"/> when it is not the control's own, or null.</summary>
    public static string? PositionEvent(A300Control control, double position) =>
        PositionEvents.TryGetValue(Short(control.Id), out var events) && events.TryGetValue(position, out var ev) ? ev : null;

    /// <summary>Controls the map reads as switches that are push buttons in the cockpit, so they are buttons, not
    /// On/Off rows, labelled by their light (<see cref="A300PanelLamps.ByButton"/>): the pressurization system
    /// buttons pick one system or the other (a press of the picked one does nothing), the stop rudder input
    /// test switches reset themselves about 6 s after a press, and each clock's elapsed time button toggles
    /// running and stopped (all measured 2026-10-10). The clock buttons are labelled by their state
    /// (<see cref="A300Clock.ButtonStates"/>).</summary>
    public static readonly IReadOnlySet<string> ButtonRows = new HashSet<string>(StringComparer.Ordinal)
    {
        "PRESS_SYS_1", "PRESS_SYS_2", "STOP_CAPT", "STOP_FO", "CPT_CLOCK_RUN", "FO_CLOCK_RUN",
    };

    /// <summary>Position words where iniBuilds' own are abbreviations or codes ("TK/GS", "SYS2"), say
    /// nothing ("OFF"/"ON" on a guard) or are wrong. The number is the POSITION, as
    /// <see cref="ParsePositions"/> reads it. The two cargo smoke agent guards were read from the
    /// aircraft's own code: their agent switch springs back to off while the guard reads 0, so 0 is
    /// closed. The yoke pitch trim switches are the other way round from their tooltips: 0 trims nose
    /// UP (measured 2026-10-06, and <c>AP::Update</c> calls the trim-up handler for 0 on both yokes).
    /// The pack mode buttons' tooltips say OFF and ON, but 0 is automatic and 1 manual (measured
    /// 2026-10-04: in 1 the pack followed its manual temperature switch, in 0 it ignored it).</summary>
    private static readonly Dictionary<string, string> PositionOverrides = new(StringComparer.Ordinal)
    {
        ["NAVATTLEFT"] = "0=Off;1=Navigate;2=Attitude",
        ["NAVATTRIGHT"] = "0=Off;1=Navigate;2=Attitude",
        ["NAVATTCTR"] = "0=Off;1=Navigate;2=Attitude",
        ["IRS_MODE_SELECT"] = "0=Test;1=Track and ground speed;2=Present position;3=Wind;4=Heading and status",
        ["IRS_SYS_DYSPL"] = "0=Off;1=System 1;2=System 2;3=System 3",
        ["PACK1_MODE"] = "0=Auto;1=Manual",
        ["PACK2_MODE"] = "0=Auto;1=Manual",
        ["PACK1_MAN"] = "0=Cold;1=Normal;2=Hot",
        ["PACK2_MAN"] = "0=Cold;1=Normal;2=Hot",
        ["TEMP_SELECT"] = "0=Forward cargo;1=Bulk cargo;2=Crew rest;3=Aft cabin;4=Mid cabin;5=Forward cabin;6=Cockpit",
        ["AC_BUS_SELECT"] = "0=Bus 1;1=Bus 2;2=Essential;3=Emergency;4=Generator 1;5=Generator 2;6=APU generator;7=External power",
        ["DC_BUS_SELECT"] = "0=Battery 1;1=Battery 2;2=Battery 3;3=Essential TR;4=TR 1;5=TR 2;6=Essential bus",
        ["COCKPIT_LOCK_SWITCH"] = "0=Lock;1=Normal;2=Unlock",
        ["COCKPIT_DOOR"] = "0=Closed;1=Open",
        ["IGNITION_KNOB"] = "0=Start B;1=Start A;2=Crank;3=Off;4=Continuous relight",
        ["AIR_XFEED"] = "0=Closed;1=Open",        // the valve: its button acts only in manual mode
        ["AIR_XFEED_AUTO"] = "0=Auto;1=Manual",
        ["FIRE_1_AG1"] = "0=Off;1=Discharged",   // the agent's discharge flag, which lights its DISCH legend
        ["FIRE_1_AG2"] = "0=Off;1=Discharged",
        ["FIRE_2_AG1"] = "0=Off;1=Discharged",
        ["FIRE_2_AG2"] = "0=Off;1=Discharged",
        ["FIRE_APU_AG"] = "0=Off;1=Discharged",
        ["FIRE_HANDLE_ENG1"] = "0=In;1=Pulled",
        ["FIRE_HANDLE_ENG2"] = "0=In;1=Pulled",
        ["FIRE_HANDLE_APU"] = "0=In;1=Pulled",
        ["CARGO_FWD_SMOKE_TOGGLE"] = "0=Agent 2;1=Off;2=Agent 1",
        ["CARGO_AFT_SMOKE_TOGGLE"] = "0=Agent 2;1=Off;2=Agent 1",
        ["NAVLIGHT_SWITCH"] = "0=System 2;1=System 1;2=Off",
        ["NOSELIGHTSWITCH"] = "0=Takeoff;1=Taxi;2=Off",
        ["ANN_LIGHTSWITCH"] = "0=Test;1=Bright;2=Dim",
        ["COMPASS_COVER"] = "0=Stowed;1=Deployed",
        ["AP_SWITCH_1"] = "0=Off;1=Engaged",
        ["AP_SWITCH_2"] = "0=Off;1=Engaged",
        ["CPT_FLT_DIR"] = "0=Off;1=Normal;2=Flight path vector",
        ["FO_FLT_DIR"] = "0=Off;1=Normal;2=Flight path vector",
        ["EFIS_MODE_CPT"] = "0=Test;1=Rose;2=Arc;3=Map;4=Plan",
        ["EFIS_MODE_FO"] = "0=Test;1=Rose;2=Arc;3=Map;4=Plan",
        ["EFIS_RANGE_CPT"] = "0=15 miles;1=30 miles;2=60 miles;3=120 miles;4=240 miles",
        ["EFIS_RANGE_FO"] = "0=15 miles;1=30 miles;2=60 miles;3=120 miles;4=240 miles",
        ["CPT_CLOCK_MODE"] = "0=Fast;1=Slow;2=Hold;3=Run;4=Off",
        ["FO_CLOCK_MODE"] = "0=Fast;1=Slow;2=Hold;3=Run;4=Off",
        ["GPWS_FLAP_SWITCH"] = "0=Off;1=Flap override;2=Normal",
        ["CPT_CONSOLE_SWITCH"] = "0=Off;1=Dim;2=Bright",
        ["FO_CONSOLE_SWITCH"] = "0=Off;1=Dim;2=Bright",
        ["ANTI_SKID"] = "0=Normal;1=Alternate, anti-skid on;2=Alternate, anti-skid off",
        ["IDC_BRT_CPT"] = "0=Bright;1=Adjust;2=Dim",
        ["IDC_BRT_FO"] = "0=Bright;1=Adjust;2=Dim",
        ["WER_MODE"] = "0=Test;1=Weather;2=Turbulence;3=Map",
        ["WER_SYS"] = "0=System 2;1=Off;2=System 1",
        ["TCAS_MODE"] = "0=Standby;1=Transponder;2=TA/RA;3=TA only",
        ["TCAS_ABV"] = "0=Above;1=Normal;2=Below",
        ["TCAS_ALT"] = "0=System 2;1=Off;2=System 1",
        ["XPDR_SWITCH"] = "0=System 1;1=System 2",
        ["MAN_GEAR_HANDLE_EXT"] = "0=Stowed;1=Extended",
        ["CPT_YOKE_TRIM"] = "0=Up;1=Neutral;2=Down",
        ["FO_YOKE_TRIM"] = "0=Up;1=Neutral;2=Down",
        ["CARGO_FWD_SMOKE_TOGGLE_GUARD"] = "0=Closed;1=Open",
        ["CARGO_AFT_SMOKE_TOGGLE_GUARD"] = "0=Closed;1=Open",
    };
}
