using System.Globalization;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using MSFSBlindAssist.Utils.Logging;

namespace MSFSBlindAssist.Aircraft.A300;

/// <summary>
/// The iniBuilds A300-600's cockpit controls, deserialized from <c>a300_control_map.json</c>.
///
/// The JSON is GENERATED by <c>tools/a300-gen/generate_a300_map.py</c> from the aircraft's own
/// compiled cockpit behaviour XML and its en-US tooltip file, and checked in so a regeneration is
/// reviewable with <c>tools/a300-gen/diff_maps.py</c>. Never hand-edit it: change the generator.
/// Every word in <see cref="A300Control.Title"/> and <see cref="A300Control.Positions"/> is
/// iniBuilds' own tooltip text; spoken names are chosen in <see cref="A300PanelLayout"/>.
///
/// It ships as an EMBEDDED RESOURCE, like the MD-11's map: a missing copied file would leave the
/// aircraft with no controls and no obvious cause.
/// </summary>
public sealed class A300ControlMap
{
    [JsonPropertyName("package_version")]
    public string PackageVersion { get; set; } = string.Empty;

    [JsonPropertyName("controls")]
    public List<A300Control> Controls { get; set; } = new();

    private readonly Dictionary<string, A300Control> _byId = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, A300Control> _byKey = new(StringComparer.Ordinal);

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    /// <summary>Built once however many threads ask at the same moment (the test classes race it).</summary>
    private static readonly Lazy<A300ControlMap> Cached =
        new(LoadEmbedded, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>The embedded map, memoized. An EMPTY map (never an exception) when it is missing
    /// or malformed: the aircraft switch must survive a broken resource, loudly logged.</summary>
    public static A300ControlMap Load() => Cached.Value;

    /// <summary>Parses map JSON and builds the indexes. Used by <see cref="Load"/> and by tests.</summary>
    public static A300ControlMap Parse(string json)
    {
        var map = JsonSerializer.Deserialize<A300ControlMap>(json, Options) ?? new A300ControlMap();
        foreach (var c in map.Controls)
        {
            map._byId.TryAdd(c.Id, c);
            map._byKey.TryAdd(c.Key, c);
        }
        return map;
    }

    /// <summary>The control with this input event id (case-insensitive), or null.</summary>
    public A300Control? Find(string id) => _byId.TryGetValue(id, out var c) ? c : null;

    /// <summary>The control with this MSFSBA variable key (<c>A300_…</c>), or null.</summary>
    public A300Control? FindByKey(string key) => _byKey.TryGetValue(key, out var c) ? c : null;

    private static A300ControlMap LoadEmbedded()
    {
        try
        {
            var asm = Assembly.GetExecutingAssembly();
            var name = Array.Find(asm.GetManifestResourceNames(),
                n => n.EndsWith("a300_control_map.json", StringComparison.OrdinalIgnoreCase));
            if (name == null)
            {
                Log.Error("A300", "a300_control_map.json embedded resource not found - the A300 will have no controls.");
                return new A300ControlMap();
            }
            using var stream = asm.GetManifestResourceStream(name);
            if (stream == null)
            {
                Log.Error("A300", $"Could not open embedded resource {name} - the A300 will have no controls.");
                return new A300ControlMap();
            }
            using var reader = new StreamReader(stream);
            var map = Parse(reader.ReadToEnd());
            Log.Info("A300", $"Control map loaded: {map.Controls.Count} controls, package {map.PackageVersion}.");
            return map;
        }
        catch (Exception ex)
        {
            Log.Error("A300", $"Failed to load a300_control_map.json: {ex.Message} - the A300 will have no controls.");
            return new A300ControlMap();
        }
    }
}

/// <summary>The control kinds the generator emits (<c>tools/a300-gen/generate_a300_map.py</c>).</summary>
public static class A300Kinds
{
    /// <summary>Two positions; the aircraft's Set event FLIPS the state whatever value is passed.</summary>
    public const string Toggle = "toggle";
    /// <summary>n positions; Set n selects position n.</summary>
    public const string Selector = "selector";
    /// <summary>A selector that springs back to <see cref="A300Control.Rest"/> (trims, cargo door).</summary>
    public const string Spring = "spring";
    /// <summary>0 to 100; Set writes the state variable (times <see cref="A300Control.Scale"/>).</summary>
    public const string Knob = "knob";
    /// <summary>Set fires a command; the position lives in <see cref="A300Control.StateVar"/> and flips.</summary>
    public const string Command = "command";
    /// <summary>Momentary: Set <see cref="A300Control.Press"/> once.</summary>
    public const string Button = "button";
    /// <summary>Set 2 is pressed, Set 0 released.</summary>
    public const string Hold = "hold";
    /// <summary>Set +1 / Set -1 steps it.</summary>
    public const string Encoder = "encoder";
    /// <summary>A guard cover: only moves the 3D model and never gates its switch.</summary>
    public const string Cover = "cover";
    /// <summary>Nothing the map can drive (the levers are hand-written in <see cref="A300Levers"/>).</summary>
    public const string None = "none";
}

/// <summary>One cockpit input event.</summary>
public sealed class A300Control
{
    /// <summary>The input event id, e.g. <c>AIRLINER_STORMLIGHT</c>.</summary>
    [JsonPropertyName("id")] public string Id { get; set; } = string.Empty;
    /// <summary>The MSFSBA variable key, e.g. <c>A300_STORMLIGHT</c>.</summary>
    [JsonPropertyName("key")] public string Key { get; set; } = string.Empty;
    /// <summary>The cockpit area from the component tree (OVERHEAD, EFIS, MIP, PEDESTAL, COCKPIT, CABIN).</summary>
    [JsonPropertyName("area")] public string Area { get; set; } = string.Empty;
    /// <summary>The cockpit panel from the component tree (OVERHEAD_FUEL, FCU, STD…).</summary>
    [JsonPropertyName("panel")] public string Panel { get; set; } = string.Empty;
    /// <summary>iniBuilds' tooltip title, e.g. "STORM LIGHT".</summary>
    [JsonPropertyName("title")] public string Title { get; set; } = string.Empty;
    [JsonPropertyName("kind")] public string Kind { get; set; } = A300Kinds.None;
    /// <summary>The B: event the cockpit's own Inc/Dec code calls, e.g. <c>AIRLINER_StormLight_Set</c>.</summary>
    [JsonPropertyName("event")] public string Event { get; set; } = string.Empty;
    /// <summary><c>L:NAME</c> or <c>A:NAME</c> holding the position or the display value; null for buttons.</summary>
    [JsonPropertyName("state_var")] public string? StateVar { get; set; }
    /// <summary>The unit an A: state variable is read in (e.g. "Bool", "Degrees").</summary>
    [JsonPropertyName("state_unit")] public string? StateUnit { get; set; }
    /// <summary>Knobs: state variable = Set value × scale (0.1 for the cabin pressure limit).</summary>
    [JsonPropertyName("scale")] public double? Scale { get; set; }
    /// <summary>Position value (as text) → iniBuilds' word for it; "" where the aircraft has none.</summary>
    [JsonPropertyName("positions")] public Dictionary<string, string> Positions { get; set; } = new();
    /// <summary>Selectors whose state value differs from the position number: position → state value.</summary>
    [JsonPropertyName("values")] public Dictionary<string, string>? Values { get; set; }
    /// <summary>Buttons and hold buttons: the Set value that presses them.</summary>
    [JsonPropertyName("press")] public double? Press { get; set; }
    /// <summary>Springs: the position they return to.</summary>
    [JsonPropertyName("rest")] public double? Rest { get; set; }
    [JsonPropertyName("note")] public string? Note { get; set; }
    /// <summary>A knob push or pull: what it does, in iniBuilds' tooltip words ("AIRCRAFT HEADING");
    /// null for every other control.</summary>
    [JsonPropertyName("action")] public string? Action { get; set; }

    /// <summary>The positions in ascending value order with iniBuilds' words.</summary>
    public IReadOnlyList<(double Value, string Label)> OrderedPositions() =>
        Positions.Select(kv => (Parse(kv.Key), kv.Value))
                 .OrderBy(p => p.Item1)
                 .ToList();

    /// <summary>What the state variable reads at <paramref name="position"/> (the position itself
    /// unless <see cref="Values"/> says otherwise).</summary>
    public double StateForPosition(double position) =>
        Values != null && Values.TryGetValue(FormatKey(position), out var v) ? Parse(v) : position;

    /// <summary>The position whose state value is <paramref name="state"/>, or null when no
    /// position reads that value.</summary>
    public double? PositionForState(double state)
    {
        foreach (var (position, _) in OrderedPositions())
            if (Math.Abs(StateForPosition(position) - state) < 0.01)
                return position;
        return null;
    }

    private static double Parse(string text) => double.Parse(text, NumberStyles.Float, CultureInfo.InvariantCulture);

    private static string FormatKey(double value) => value.ToString("0.####", CultureInfo.InvariantCulture);
}
