namespace MSFSBlindAssist.Aircraft.L1011;

public static partial class L1011PanelLayout
{
    /// <summary>
    /// The flight engineer's station, in the order of the manual's cockpit safety inspection and
    /// flight-engineer station preparation: circuit breakers, lights, oxygen, electrical, APU, fire and overheat tests,
    /// brake temperature, hydraulics, fuel, jettison and engine fuel, oil and vibration, bleed air,
    /// air conditioning, pressurization, slat monitor, aural warning, movies and waste water, and the
    /// cockpit door behind the engineer's seat.
    /// </summary>
    private static L1011LayoutPanel[] EngineerPanels() => new[]
    {
        P("Circuit Breakers",
            R(L1011Levers.BreakerListKey, "Open circuit breaker list")),

        P("Engineer Lights and Annunciators",
            R("SWITCH_FE_CB_TEST", "Annunciator light test"),
            R("SWITCH_FE_WARNING_TEST", "Annunciator light intensity"),
            R("ROTARY_FE_LIGHTS_PANEL", "Panel lights"),
            R("ROTARY_FE_LIGHTS_INSTR_KGS", "Instrument lights, kilogram panel"),
            R("ROTARY_FE_LIGHTS_INSTR_LBS", "Instrument lights, pound panel"),
            R("ROTARY_FE_LIGHTS_FLOOD", "Flood lights"),
            R("ROTARY_FE_LIGHTS_DESK", "Desk light"),
            R("SWITCH_FE_UTILITY_BRT", "Utility light"),
            R("ROTARY_FE_LIGHTS_CB_FWD", "Forward circuit breaker lights"),
            R("ROTARY_FE_LIGHTS_CB_AFT", "Aft circuit breaker lights")),

        P("Passenger Oxygen",
            R("GUARD_PAX_OXY_MANUAL", "Passenger oxygen guard"),
            R("SWITCH_PAX_OXY_MANUAL", "Passenger oxygen manual")),

        P("Electrical",
            R("TOGGLE_BATTERY", "Battery"),
            R("GUARD_STBY_POWER", "Standby power guard"),
            R("TOGGLE_STBY_POWER", "Standby power", "0=Off;1=Arm;2=On"),
            R("ROTARY_AC_ESS_BUS", "AC essential bus selector"),
            R("SWITCH_DC_BUS_ISO", "DC bus isolation"),
            R("TOGGLE_EXT_PWR", "External power"),
            R("TOGGLE_GND_APU", "Ground service bus", "0=APU;1=Off;2=External power"),
            R("SWITCH_GALLEY_BUS_1", "Galley 1 power"),
            R("SWITCH_GALLEY_BUS_2", "Galley 2 power"),
            R("SWITCH_GALLEY_BUS_3", "Galley 3 power"),
            R("GUARD_DISCO_IDG_1", "IDG 1 disconnect guard"),
            R("SWITCH_DISCO_IDG_1", "IDG 1 disconnect"),
            R("GUARD_DISCO_IDG_2", "IDG 2 disconnect guard"),
            R("SWITCH_DISCO_IDG_2", "IDG 2 disconnect"),
            R("GUARD_DISCO_IDG_3", "IDG 3 disconnect guard"),
            R("SWITCH_DISCO_IDG_3", "IDG 3 disconnect"),
            R("SWITCH_BRG_GEN_1", "Generator 1 field close"),
            R("SWITCH_TRIP_GEN_1", "Generator 1 field trip"),
            R("SWITCH_GEN_FLOW_1", "Generator 1 breaker close"),
            R("SWITCH_GEN_FLOW_OPEN_1", "Generator 1 breaker trip"),
            R("SWITCH_BRG_GEN_2", "Generator 2 field close"),
            R("SWITCH_TRIP_GEN_2", "Generator 2 field trip"),
            R("SWITCH_GEN_FLOW_2", "Generator 2 breaker close"),
            R("SWITCH_GEN_FLOW_OPEN_2", "Generator 2 breaker trip"),
            R("SWITCH_BRG_GEN_3", "Generator 3 field close"),
            R("SWITCH_TRIP_GEN_3", "Generator 3 field trip"),
            R("SWITCH_GEN_FLOW_3", "Generator 3 breaker close"),
            R("SWITCH_GEN_FLOW_OPEN_3", "Generator 3 breaker trip"),
            R("SWITCH_APU_BRG", "APU generator field close"),
            R("SWITCH_APU_TRIP", "APU generator field trip"),
            R("SWITCH_GND_FLOW", "APU generator breaker close"),
            R("SWITCH_GND_FLOW_OPEN", "APU generator breaker trip"),
            R("SWITCH_TIE_FLOW_1", "AC tie 1 close"),
            R("SWITCH_BUS_1_BREAKER", "AC tie 1 trip"),
            R("SWITCH_TIE_FLOW_2", "AC tie 2 close"),
            R("SWITCH_BUS_2_BREAKER", "AC tie 2 trip"),
            R("SWITCH_TIE_FLOW_3", "AC tie 3 close"),
            R("SWITCH_BUS_3_BREAKER", "AC tie 3 trip"),
            R("ROTARY_PWR_SOURCE", "AC meter selector"),
            R("ROTARY_STBY_DC_BUS", "DC meter selector"),
            R("SWITCH_ELEC_KVAR", "KW KVAR display button"),
            R("SWITCH_PMG_TEST", "PMG test"),
            R("SWITCH_IDG_OIL_TEMP", "IDG temperature rise button")),

        P("APU",
            R("TOGGLE_APU_POWER", "APU master"),
            R("SWITCH_APU_MODE", "APU compressor mode", "0=Minimum;1=Normal;2=Maximum"),
            R("SWITCH_APU_START", "APU start"),
            R("APU_STOP", "APU stop"),
            R("SWITCH_APU_BLEED", "APU bleed"),
            R("GUARD_APU_AUTOFIRE", "APU auto fire shutdown guard"),
            R("SWITCH_APU_AUTOFIRE", "APU auto fire shutdown")),

        P("Fire Detection",
            R("ROTARY_FIRE_DETECT_TEST_ENG_1", "Engine 1 fire loop selector", "0=Loop B"),
            R("ROTARY_FIRE_DETECT_TEST_ENG_2", "Engine 2 fire loop selector", "0=Loop B"),
            R("ROTARY_FIRE_DETECT_TEST_ENG_3", "Engine 3 fire loop selector", "0=Loop B"),
            R("ROTARY_FIRE_DETECT_TEST_APU", "APU fire loop selector", "0=Loop B"),
            R("SWITCH_FIRE_DETECT_TEST_A", "Fire loop test A"),
            R("SWITCH_FIRE_DETECT_TEST_B", "Fire loop test B"),
            R("SWITCH_FIRE_DETECT_BELL", "Fire bell cutout"),
            R("ROTARY_PYLON_OVHT_ENG_1", "Engine 1 nacelle loop selector", "0=Loop A;1=Both loops;2=Loop B"),
            R("ROTARY_PYLON_OVHT_ENG_2", "Engine 2 nacelle loop selector", "0=Loop A;1=Both loops;2=Loop B"),
            R("ROTARY_PYLON_OVHT_ENG_3", "Engine 3 nacelle loop selector", "0=Loop A;1=Both loops;2=Loop B"),
            R("SWITCH_PYLON_OVHT_TEST", "Nacelle loop test"),
            R("SWITCH_TURB_OVHT_TEST_A", "Turbine overheat test A"),
            R("SWITCH_TURB_OVHT_TEST_B", "Turbine overheat test B"),
            R("ROTARY_WHEEL_WELL_TEST", "Wheel well loop selector", "0=Loop A;1=Both loops;2=Loop B"),
            R("SWITCH_WHEEL_WELL_TEST_A", "Wheel well loop test A"),
            R("SWITCH_WHEEL_WELL_TEST_B", "Wheel well loop test B"),
            R("ROTARY_AREA_OVHT", "Area overheat loop selector"),
            R("SWITCH_AREA_OVHT_TEST", "Area overheat test")),

        P("APU Fire",
            R("HANDLE_FIRE_APU", "APU fire handle", "0=In;1=Pulled"),
            R("SWITCH_APU_DISCH", "APU fire bottle discharge", "0=Left;1=Centre;2=Right"),
            R("SWITCH_EXTING_TEST", "Fire warning test"),
            R("SWITCH_EXTING_SHORT", "Fire warning short test")),

        P("Cargo Fire and Smoke Detection",
            R("SWITCH_FWD_CARGO_DETECT_SEL", "Forward cargo detector loop", "0=Loop A;1=Both loops;2=Loop B"),
            R("SWITCH_FWD_CARGO_DETECT_TEST", "Forward cargo detector test"),
            R("SWITCH_FWD_CARGO_SHORT_TEST", "Forward cargo short test"),
            R("SWITCH_FWD_CARGO_TONE", "Forward cargo tone cutout"),
            R("GUARD_FWD_CARGO_EXT_MAIN", "Forward cargo main extinguisher guard"),
            R("SWITCH_FWD_CARGO_EXT_MAIN", "Forward cargo main extinguisher"),
            R("GUARD_FWD_CARGO_EXT_ALTN", "Forward cargo alternate extinguisher guard"),
            R("SWITCH_FWD_CARGO_EXT_ALTN", "Forward cargo alternate extinguisher"),
            R("SWITCH_SMOKE_DETECT_SELECT", "Smoke detection circuit"),
            R("SWITCH_SMOKE_DETECT_TEST", "Smoke detection test"),
            R("SWITCH_SMOKE_DETECT_TONE", "Smoke detection tone cutout"),
            R("SWITCH_GALLEY_SMOKE_TEST", "Galley smoke test")),

        P("Brake Temperature",
            R("SWITCH_BRAKE_TEMP_TEST", "Brake temperature test"),
            R("SWITCH_BRAKE_TEMP_LF", "Left forward brake"),
            R("SWITCH_BRAKE_TEMP_LR", "Left rear brake"),
            R("SWITCH_BRAKE_TEMP_RF", "Right forward brake"),
            R("SWITCH_BRAKE_TEMP_RR", "Right rear brake")),

        P("Hydraulics",
            R("GUARD_HYD_PUMP_A1", "System A engine pump guard"),
            R("SWITCH_HYD_PUMP_A1", "System A engine pump"),
            R("GUARD_HYD_PUMP_B1", "System B engine pump guard"),
            R("SWITCH_HYD_PUMP_B1", "System B engine pump"),
            R("GUARD_HYD_PUMP_C1", "System C engine pump guard"),
            R("SWITCH_HYD_PUMP_C1", "System C engine pump"),
            R("GUARD_HYD_PUMP_D1", "System D engine pump guard"),
            R("SWITCH_HYD_PUMP_D1", "System D engine pump"),
            R("ROTARY_HYD_B2_MODE", "System B ATM"),
            R("ROTARY_HYD_C2_MODE", "System C ATM"),
            R("SWITCH_HYD_AC_PUMP_B3", "System B AC pump"),
            R("SWITCH_HYD_AC_PUMP_C3", "System C AC pump"),
            R("SWITCH_PTU_AB", "A to B power transfer unit"),
            R("SWITCH_PTU_CD", "C to D power transfer unit"),
            R("GUARD_HYD_RAT", "Ram air turbine guard"),
            R("SWITCH_HYD_RAT", "Ram air turbine")),

        P("Fuel",
            R("SWITCH_FUEL_PUMP_1_1", "Tank 1 pump 1"),
            R("SWITCH_FUEL_PUMP_1_2", "Tank 1 pump 2"),
            R("SWITCH_FUEL_PUMP_2L_1", "Tank 2 left pump 1"),
            R("SWITCH_FUEL_PUMP_2L_2", "Tank 2 left pump 2"),
            R("SWITCH_FUEL_PUMP_2R_1", "Tank 2 right pump 1"),
            R("SWITCH_FUEL_PUMP_2R_2", "Tank 2 right pump 2"),
            R("SWITCH_FUEL_PUMP_3_1", "Tank 3 pump 1"),
            R("SWITCH_FUEL_PUMP_3_2", "Tank 3 pump 2"),
            R("SWITCH_FUEL_LEFT_XFEED", "Left crossfeed"),
            R("SWITCH_FUEL_CTR_XFEED", "Center crossfeed"),
            R("SWITCH_FUEL_RIGHT_XFEED", "Right crossfeed"),
            R("GUARD_ENG_1_TANK_VALVE", "Engine 1 tank valve guard"),
            R("SWITCH_ENG_1_TANK_VALVE", "Engine 1 tank valve"),
            R("GUARD_ENG_2_TANK_VALVE", "Engine 2 tank valve guard"),
            R("SWITCH_ENG_2_TANK_VALVE", "Engine 2 tank valve"),
            R("GUARD_ENG_3_TANK_VALVE", "Engine 3 tank valve guard"),
            R("SWITCH_ENG_3_TANK_VALVE", "Engine 3 tank valve"),
            R("SWITCH_FUEL_XFR_1A", "Tank 1A transfer"),
            R("SWITCH_FUEL_XFR_3A", "Tank 3A transfer"),
            R("GUARD_FUEL_GRAVITY_1A", "Tank 1A gravity transfer guard"),
            R("SWITCH_FUEL_GRAVITY_1A", "Tank 1A gravity transfer"),
            R("GUARD_FUEL_GRAVITY_3A", "Tank 3A gravity transfer guard"),
            R("SWITCH_FUEL_GRAVITY_3A", "Tank 3A gravity transfer"),
            R("SWITCH_FUEL_QTY_2L", "Tank 2 left inboard quantity"),
            R("SWITCH_FUEL_QTY_2R", "Tank 2 right inboard quantity"),
            R("SWITCH_FUEL_QTY_1A", "Tank 1A quantity"),
            R("SWITCH_FUEL_QTY_3A", "Tank 3A quantity"),
            R("ROTARY_TANK_TEMP_SEL", "Fuel temperature selector",
                "0=Tank 2 left;1=Engine 1 inlet;2=Engine 2 inlet;3=Engine 3 inlet"),
            R("SWITCH_FUEL_QTY_TEST", "Fuel quantity test"),
            R("SWITCH_FUEL_TEMP_TEST", "Fuel temperature test"),
            R("SWITCH_REFUEL_POWER", "Refuel power")),

        P("Fuel Jettison and Engine Fuel",
            R("GUARD_FUEL_DUMP_MASTER", "Jettison master guard"),
            R("SWITCH_FUEL_DUMP_MASTER", "Jettison master"),
            R("GUARD_FUEL_DUMP_2L", "Tank 2 left dump guard"),
            R("SWITCH_FUEL_DUMP_2L", "Tank 2 left dump"),
            R("GUARD_FUEL_DUMP_1", "Tank 1 dump guard"),
            R("SWITCH_FUEL_DUMP_1", "Tank 1 dump"),
            R("GUARD_FUEL_DUMP_3", "Tank 3 dump guard"),
            R("SWITCH_FUEL_DUMP_3", "Tank 3 dump"),
            R("GUARD_FUEL_DUMP_2R", "Tank 2 right dump guard"),
            R("SWITCH_FUEL_DUMP_2R", "Tank 2 right dump"),
            R("GUARD_FUEL_CTRL_OVRD_ENG_1", "Engine 1 fuel control amplifier guard"),
            R("SWITCH_FUEL_CTRL_OVRD_ENG_1", "Engine 1 fuel control amplifier"),
            R("GUARD_FUEL_CTRL_OVRD_ENG_2", "Engine 2 fuel control amplifier guard"),
            R("SWITCH_FUEL_CTRL_OVRD_ENG_2", "Engine 2 fuel control amplifier"),
            R("GUARD_FUEL_CTRL_OVRD_ENG_3", "Engine 3 fuel control amplifier guard"),
            R("SWITCH_FUEL_CTRL_OVRD_ENG_3", "Engine 3 fuel control amplifier"),
            R("ROTARY_FUEL_USED_ENG_1", "Engine 1 fuel used test"),
            R("ROTARY_FUEL_USED_ENG_2", "Engine 2 fuel used test"),
            R("ROTARY_FUEL_USED_ENG_3", "Engine 3 fuel used test")),

        P("Engine Oil and Vibration",
            R("SWITCH_OIL_FILTER_TEST", "Oil indicator test"),
            R("SWITCH_OIL_TEMP_ENG_1", "Engine 1 oil temperature test"),
            R("SWITCH_OIL_TEMP_ENG_2", "Engine 2 oil temperature test"),
            R("SWITCH_OIL_TEMP_ENG_3", "Engine 3 oil temperature test"),
            R("SWITCH_OIL_QTY_ENG_1", "Engine 1 oil quantity test"),
            R("SWITCH_OIL_QTY_ENG_2", "Engine 2 oil quantity test"),
            R("SWITCH_OIL_QTY_ENG_3", "Engine 3 oil quantity test"),
            R("SWITCH_N2_ENG_1", "Engine 1 N2 tachometer test"),
            R("SWITCH_N2_ENG_2", "Engine 2 N2 tachometer test"),
            R("SWITCH_N2_ENG_3", "Engine 3 N2 tachometer test"),
            R("N2_TEST_ENG_1", "Engine 1 N2 indicator test"),
            R("N2_TEST_ENG_2", "Engine 2 N2 indicator test"),
            R("N2_TEST_ENG_3", "Engine 3 N2 indicator test"),
            R("SWITCH_STATUS_PICKUP_A", "Vibration pickup A"),
            R("SWITCH_STATUS_PICKUP_B", "Vibration pickup B"),
            R("ROTARY_ENG_STATUS", "Vibration filter"),
            R("LX_STAUS_TEST", "Vibration test")),

        P("Bleed Air",
            R("SWITCH_HI_PRESS_ENG_1", "Engine 1 high pressure valve"),
            R("SWITCH_HI_PRESS_ENG_2", "Engine 2 high pressure valve"),
            R("SWITCH_HI_PRESS_ENG_3", "Engine 3 high pressure valve"),
            R("SWITCH_ISLN_VALVE_ENG_1", "Engine 1 isolation valve"),
            R("SWITCH_ISLN_VALVE_ENG_2", "Engine 2 isolation valve"),
            R("SWITCH_ISLN_VALVE_ENG_3", "Engine 3 isolation valve"),
            R("SWITCH_XBLEED_1", "Crossbleed valve 1"),
            R("SWITCH_XBLEED_3", "Crossbleed valve 3"),
            R("SWITCH_APU_ISLN_VALVE", "Fuselage isolation valve"),
            R("SWITCH_HOT_AIR_ENG_1", "Hot air valve 1"),
            R("SWITCH_HOT_AIR_ENG_3", "Hot air valve 3"),
            R("SWITCH_ISLN_VALVE_OVHT_2A", "Hot air isolation valve 2A"),
            R("SWITCH_ISLN_VALVE_OVHT_2B", "Hot air isolation valve 2B")),

        P("Air Conditioning",
            R("SWITCH_PACK_FLOW_ENG_1", "Pack 1 flow"),
            R("SWITCH_PACK_FLOW_ENG_2", "Pack 2 flow"),
            R("SWITCH_PACK_FLOW_ENG_3", "Pack 3 flow"),
            R("SWITCH_BLEED_PLENUM_ENG_1", "Pack 1 mode"),
            R("SWITCH_BLEED_PLENUM_ENG_2", "Pack 2 mode", "0=Manual;1=Auto"),
            R("SWITCH_BLEED_PLENUM_ENG_3", "Pack 3 mode", "0=Manual;1=Auto"),
            R("SWITCH_BLEED_1_COOL", "Pack 1 manual cool"),
            R("SWITCH_BLEED_1_WARM", "Pack 1 manual warm"),
            R("SWITCH_BLEED_2_COOL", "Pack 2 manual cool"),
            R("SWITCH_BLEED_2_WARM", "Pack 2 manual warm"),
            R("SWITCH_BLEED_3_COOL", "Pack 3 manual cool"),
            R("SWITCH_BLEED_3_WARM", "Pack 3 manual warm"),
            R("SWITCH_RAM_AUTO", "Ground control"),
            R("SWITCH_FLT_STA_CLOSE", "Flight station zone trim"),
            R("SWITCH_FWD_CAB_CLOSE", "Forward cabin zone trim"),
            R("SWITCH_MID_CAB_CLOSE", "Mid cabin zone trim"),
            R("SWITCH_AFT_CAB_CLOSE", "Aft cabin zone trim"),
            R("ROTARY_FLT_STA", "Flight station temperature"),
            R("ROTARY_FWD_CAB", "Forward cabin temperature"),
            R("ROTARY_MID_CAB", "Mid cabin temperature"),
            R("ROTARY_AFT_CAB", "Aft cabin temperature"),
            R("ROTARY_PACK_SELECT", "Pack temperature display", "0=Pack 1;1=Pack 2;2=Pack 3"),
            R("ROTARY_PACK_MODE", "ECS temperature selector",
                "0=Position 1;1=Position 2;2=Position 3;3=Position 4;4=Position 5"),
            R("ROTARY_PACK_AREA", "Zone temperature display",
                "0=Position 1;1=Position 2;2=Position 3;3=Position 4;4=Position 5"),
            R("SWITCH_TEMP_SELECT", "Zone or duct temperature"),
            R("SWITCH_COOL_AIR_OVBD", "Overboard cooling"),
            R("SWITCH_CARGO_HEAT_FWD", "Forward cargo heat"),
            R("SWITCH_CARGO_HEAT_MID", "Mid cargo heat"),
            R("SWITCH_CARGO_HEAT_AFT", "Aft cargo heat"),
            R("SWITCH_INS_COOLING", "INS cooling"),
            R("SWITCH_HUMIDITY_AIR", "Humidifier")),

        P("Pressurization",
            R("ROTARY_CAB_PRESS_MODE", "Pressurization mode", "0=Auto;1=Standby;2=Manual"),
            R("ROTARY_FLT_CAB", "Cabin altitude"),
            R("ROTARY_CAB_PRESS", "Barometric pressure"),
            R("ROTARY_CABIN_BARO", "Cabin barometric setting"),
            R("ROTARY_CAB_PRESS_NORM", "Normal rate"),
            R("ROTARY_CAB_PRESS_STBY", "Standby rate"),
            R("SWITCH_CAB_PRESS_FWD_MNL", "Forward outflow valve manual"),
            R("SWITCH_CAB_PRESS_AFT_MNL", "Aft outflow valve manual")),

        P("Slat Monitor",
            R("SWITCH_SLAT_MONITOR", "Slat segment lights"),
            R("GUARD_FE_SLAT_LOCK", "Slat lock guard"),
            R("SWITCH_FE_SLAT_LOCK", "Slat lock")),

        P("Aural Warning, Movies and Waste Water",
            R("SWITCH_AURAL_WARN_MODE", "Aural warning test selector",
                "0=Position 1;1=Position 2;2=Position 3;3=Position 4;4=Position 5"),
            R("SWITCH_AURAL_WARN_TEST", "Aural warning test"),
            R("GUARD_MOVIES_OFF", "Movie cutoff guard"),
            R("MOVIES_OFF", "Movie cutoff"),
            R("LX_WASTE_WATER_PUMP", "Waste water pump"),
            R("SWITCH_WASTE_WATER_MID", "Mid drain mast heater"),
            R("SWITCH_WASTE_WATER_AFT", "Aft drain mast heater")),

        P("Cockpit Door",
            R("COCKPIT_DOOR", "Cockpit door")),
    };
}
