namespace MSFSBlindAssist.Aircraft.L1011;

public static partial class L1011PanelLayout
{
    /// <summary>
    /// The overhead, in the order of the manual's overhead preparation: INS mode selectors, fire
    /// handles, compass, lighting, master radio, wipers, anti-ice, window heat, air data heat,
    /// Mach feel and rudder limiter, voice recorder, engine start, primary flight controls, flight
    /// control electronics, anti-skid and autobrake, exterior lights, emergency lights and signs,
    /// evacuation, cabin interphone.
    /// </summary>
    private static L1011LayoutPanel[] OverheadPanels() => new[]
    {
        P("INS Mode Selectors",
            R("ROTARY_INS_MODE_1", "INS 1 mode"),
            R("ROTARY_INS_MODE_2", "INS 2 mode"),
            R("ROTARY_INS_MODE_3", "INS 3 mode")),

        P("Engine Fire Handles",
            R("HANDLE_FIRE_1", "Engine 1 fire handle", "0=In;1=Pulled"),
            R("SWITCH_ENG_1_DISCH", "Engine 1 fire bottle discharge", "0=Left;1=Centre;2=Right"),
            R("HANDLE_FIRE_2", "Engine 2 fire handle", "0=In;1=Pulled"),
            R("SWITCH_ENG_2_DISCH", "Engine 2 fire bottle discharge", "0=Left;1=Centre;2=Right"),
            R("HANDLE_FIRE_3", "Engine 3 fire handle", "0=In;1=Pulled"),
            R("SWITCH_ENG_3_DISCH", "Engine 3 fire bottle discharge", "0=Left;1=Centre;2=Right")),

        P("Compass",
            R("SWITCH_COMPASS_1_MAG", "Compass 1 magnetic"),
            R("ROTARY_COMPASS_1_SET", "Compass 1 heading set", "2=Centre"),
            R("SWITCH_COMPASS_2_MAG", "Compass 2 magnetic"),
            R("ROTARY_COMPASS_2_SET", "Compass 2 heading set", "2=Centre")),

        P("Overhead Lighting",
            R("SWITCH_LIGHTS_TEST", "Annunciator light test"),
            R("SWITCH_LIGHTS_BRT", "Annunciator intensity"),
            R("ROTARY_PANEL_LIGHTS", "Overhead panel lights"),
            R("ROTARY_OVERHEAD_LIGHTS", "Overhead lights"),
            R("ROTARY_OVH_EYEBROW_LIGHT", "Eyebrow panel light"),
            R("ROTARY_PEDESTAL_FLOOD", "Center console flood light"),
            R("ROTARY_COMPASS_LIGHT", "Magnetic compass light"),
            R("SWITCH_OVH_LIGHTS", "Ceiling lights master"),
            R("TOGGLE_INSTR_STBY_LIGHTS", "Standby instrument lights"),
            R("EYE_LOCATOR_LIGHT", "Eye locator light"),
            R("GUARD_STORM_LIGHT", "Thunderstorm light guard"),
            R("SWITCH_STORM_LIGHT", "Thunderstorm light")),

        P("Master Radio",
            R("SWITCH_MASTER_RADIO_ESS", "Essential master radio"),
            R("SWITCH_MASTER_RADIO_NO2", "Number 2 master radio")),

        P("Wipers and Rain Repellent",
            R("ROTARY_CPT_WIPER", "Captain wiper"),
            R("SWITCH_CPT_REPELLANT", "Captain rain repellent"),
            R("SWITCH_CPT_WIPER_WASHER", "Captain washer"),
            R("ROTARY_FO_WIPER", "First officer wiper"),
            R("SWITCH_FO_REPELLANT", "First officer rain repellent"),
            R("SWITCH_FO_WIPER_WASHER", "First officer washer")),

        P("Anti-Ice",
            R("SWITCH_ANTI_ICE_LEFT_AUTO", "Left wing anti-ice auto"),
            R("SWITCH_ANTI_ICE_LEFT_MAN", "Left wing anti-ice manual"),
            R("SWITCH_ANTI_ICE_RIGHT_AUTO", "Right wing anti-ice auto"),
            R("SWITCH_ANTI_ICE_RIGHT_MAN", "Right wing anti-ice manual"),
            R("SWITCH_ANTI_ICE_WING_TEST", "Wing anti-ice test"),
            R("SWITCH_ANTI_ICE_ENG_1", "Engine 1 anti-ice"),
            R("SWITCH_ANTI_ICE_ENG_2", "Engine 2 anti-ice"),
            R("SWITCH_ANTI_ICE_ENG_3", "Engine 3 anti-ice")),

        P("Window Heat",
            R("SWITCH_ANTI_ICE_CPT", "Captain windshield heat"),
            R("SWITCH_ANTI_ICE_FO", "First officer windshield heat"),
            R("SWITCH_ANTI_ICE_L_FWD", "Left forward window heat"),
            R("SWITCH_ANTI_ICE_L_REAR", "Left rear window heat"),
            R("SWITCH_ANTI_ICE_R_FWD", "Right forward window heat"),
            R("SWITCH_ANTI_ICE_R_REAR", "Right rear window heat"),
            R("SWITCH_ANTI_ICE_DEFOG", "Defog fan"),
            R("SWITCH_ANTI_ICE_TEST", "Window heat test")),

        P("Air Data Heat",
            R("SWITCH_CPT_PITOT_HEAT", "Captain pitot heat"),
            R("SWITCH_FO_PITOT_HEAT", "First officer pitot heat"),
            R("SWITCH_PROBE_HEAT", "Temperature probe heat"),
            R("SWITCH_ALPHA_HEAT", "Angle of attack probe heat"),
            R("SWITCH_PITOT_MAST_LIGHT", "Pitot mast light test")),

        P("Mach Feel and Rudder Limiter",
            R("SWITCH_MACH_FEEL_1", "Mach feel 1"),
            R("SWITCH_MACH_FEEL_2", "Mach feel 2"),
            R("SWITCH_RUDDER_LIMITER", "Rudder limiter")),

        P("Voice Recorder",
            R("SWITCH_CVR_TEST", "Voice recorder test"),
            R("SWITCH_CVR_ERASE", "Voice recorder erase")),

        P("Engine Start",
            R("ROTARY_ENG_START_SEL", "Ignition selector"),
            R("SWITCH_CONT_IGNITION", "Continuous ignition"),
            R("SWITCH_GND_START_ENG_1", "Engine 1 ground start"),
            R("SWITCH_GND_START_ENG_2", "Engine 2 ground start"),
            R("SWITCH_GND_START_ENG_3", "Engine 3 ground start"),
            R("SWITCH_GND_START", "Ground start release"),
            R("SWITCH_AIR_START_ENG_1", "Engine 1 windmill start"),
            R("SWITCH_AIR_START_ENG_2", "Engine 2 windmill start"),
            R("SWITCH_AIR_START_ENG_3", "Engine 3 windmill start")),

        P("Primary Flight Controls",
            R("SWITCH_PFCS_PITCH_1", "Pitch monitor 1"),
            R("SWITCH_PFCS_PITCH_2", "Pitch monitor 2"),
            R("SWITCH_PFCS_ROLL_1", "Roll monitor 1"),
            R("SWITCH_PFCS_ROLL_2", "Roll monitor 2"),
            R("GUARD_PFCS_RUDDER", "Rudder switch guard"),
            R("SWITCH_PFCS_RUDDER", "Rudder"),
            R("SWITCH_STABILIZER_A", "Left stabilizer servo A"),
            R("SWITCH_STABILIZER_B", "Left stabilizer servo B"),
            R("SWITCH_STABILIZER_C", "Right stabilizer servo C"),
            R("SWITCH_STABILIZER_D", "Right stabilizer servo D"),
            R("SWITCH_AILERON_L_OUTBD", "Left outboard aileron"),
            R("SWITCH_AILERON_L_INBD", "Left inboard aileron"),
            R("SWITCH_AILERON_R_INBD", "Right inboard aileron"),
            R("SWITCH_AILERON_R_OUTBD", "Right outboard aileron"),
            R("SWITCH_SPOILER_L56", "Spoilers left 5 and 6"),
            R("SWITCH_SPOILER_LR4", "Spoilers 4"),
            R("SWITCH_SPOILER_LR1", "Spoilers 1"),
            R("SWITCH_SPOILER_LR2", "Spoilers 2"),
            R("SWITCH_SPOILER_LR3", "Spoilers 3"),
            R("SWITCH_SPOILER_R56", "Spoilers right 5 and 6")),

        P("Flight Control Electronics",
            R("SWITCH_ACS_1", "ACS channel 1"),
            R("SWITCH_ACS_2", "ACS channel 2"),
            R("SWITCH_YAW_SAS_1", "Yaw SAS 1"),
            R("SWITCH_YAW_SAS_2", "Yaw SAS 2"),
            R("SWITCH_STALL_WARN_1", "Stall warning 1"),
            R("SWITCH_STALL_WARN_2", "Stall warning 2"),
            R("SWITCH_STALL_WARN_TEST", "Stall warning test"),
            R("SWITCH_PITCH_TRIM_1", "Pitch trim channel 1"),
            R("SWITCH_PITCH_TRIM_2", "Pitch trim channel 2"),
            R("SWITCH_DLC_AUTO_1", "DLC channel 1"),
            R("SWITCH_DLC_AUTO_2", "DLC channel 2"),
            R("SWITCH_ATS_1", "Autothrottle system channel 1"),
            R("SWITCH_ATS_2", "Autothrottle system channel 2"),
            R("SWITCH_MACH_TRIM_1", "Mach trim channel 1"),
            R("SWITCH_MACH_TRIM_2", "Mach trim channel 2")),

        P("Antiskid and Autobrake",
            R("SWITCH_ANTISKID_ON", "Anti-skid"),
            R("SWITCH_ANTISKID_NORM_TEST", "Anti-skid normal test"),
            R("SWITCH_ANTISKID_ALT_TEST", "Anti-skid alternate test"),
            R("ROTARY_AUTO_BRAKE_MODE", "Autobrake"),
            R("SWITCH_AUTO_BRAKE_ARMED", "Autobrake arm")),

        P("Exterior Lights",
            R("SWITCH_POSITION_LIGHT", "Position lights"),
            R("SWITCH_ANTICOL_LIGHT", "Anti-collision lights"),
            R("SWITCH_STROBE_LIGHT", "Strobe lights"),
            R("TOGGLE_LOGO_LIGHT", "Logo lights"),
            R("SWITCH_FLOOD_LIGHT", "Wing lights"),
            R("SWITCH_WHEEL_LIGHT", "Wheel well lights"),
            R("TOGGLE_LANDING_LEFT", "Left landing light"),
            R("TOGGLE_LANDING_RIGHT", "Right landing light"),
            R("TOGGLE_LANDING_NOSE", "Nose landing light"),
            R("TOGGLE_TAXI_LIGHT", "Taxi light"),
            R("TOGGLE_RWY_TURNOFF", "Runway turnoff lights")),

        P("Emergency Lights and Signs",
            R("GUARD_EMER_LIGHTING", "Emergency lights guard"),
            R("TOGGLE_EMER_LIGHTING", "Emergency lights", "0=Off;1=Arm;2=On"),
            R("SWITCH_SEATBELT_LIGHT", "Seat belt signs"),
            R("SWITCH_SMOKING_LIGHT", "No smoking signs")),

        P("Evacuation",
            R("GUARD_EVAC_COMMAND", "Evacuation command guard"),
            R("SWITCH_EVAC_COMMAND", "Evacuation command"),
            R("SWITCH_EVAC_HORN", "Evacuation horn cutout")),

        P("Cabin Interphone",
            R("ROTARY_CABIN_CALL", "Interphone station"),
            R("SWITCH_CABIN_CALL_STA", "Station call"),
            R("SWITCH_CABIN_CALL_SIG", "Call signal"),
            R("SWITCH_CABIN_CALL_ALL", "All stations call"),
            R("SWITCH_CABIN_CALL_GND", "Ground crew call"),
            R("SWITCH_CABIN_CALL_RESET", "Call reset"),
            R("ROTARY_PAX_MONITOR", "Passenger address monitor")),
    };
}
