using System.Globalization;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using MSFSBlindAssist.Utils.Logging;

namespace MSFSBlindAssist.Aircraft.L1011;

/// <summary>
/// The iniBuilds L-1011 TriStar's cockpit controls, deserialized from <c>l1011_control_map.json</c>.
///
/// The JSON is GENERATED by <c>tools/l1011-gen/generate_l1011_map.py</c> from the aircraft's own
/// compiled cockpit behavior XML and its en-US tooltip file, and checked in so a regeneration is
/// reviewable with <c>tools/l1011-gen/diff_maps.py</c>. Never hand-edit it: change the generator.
/// Every word in <see cref="L1011Control.Title"/> and <see cref="L1011Control.Positions"/> is
/// iniBuilds' own tooltip text; spoken names are chosen in <see cref="L1011PanelLayout"/>.
///
/// It ships as an EMBEDDED RESOURCE for the same reason as the MD-11's map: a missing copied
/// file would leave the aircraft with no controls and no obvious cause.
/// </summary>
public sealed class L1011ControlMap
{
    [JsonPropertyName("package_version")]
    public string PackageVersion { get; set; } = string.Empty;

    [JsonPropertyName("controls")]
    public List<L1011Control> Controls { get; set; } = new();

    [JsonPropertyName("breakers")]
    public List<L1011Breaker> Breakers { get; set; } = new();

    /// <summary>Every L:var an emissive (lamp) material of the cockpit model reads, for review.</summary>
    [JsonPropertyName("lamps")]
    public List<string> Lamps { get; set; } = new();

    private Dictionary<string, L1011Control> _byId = new(StringComparer.OrdinalIgnoreCase);

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    /// <summary>Built once however many threads ask at the same moment (the test classes race it).</summary>
    private static readonly Lazy<L1011ControlMap> Cached =
        new(LoadEmbedded, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>The embedded map, memoized. An EMPTY map (never an exception) when it is missing
    /// or malformed: the aircraft switch must survive a broken resource, loudly logged.</summary>
    public static L1011ControlMap Load() => Cached.Value;

    /// <summary>Parses map JSON and builds the id index. Used by <see cref="Load"/> and by tests.</summary>
    public static L1011ControlMap Parse(string json)
    {
        var map = JsonSerializer.Deserialize<L1011ControlMap>(json, Options) ?? new L1011ControlMap();
        foreach (var c in map.Controls)
            map._byId.TryAdd(c.Id, c);
        return map;
    }

    /// <summary>The control with this id (case-insensitive), or null.</summary>
    public L1011Control? Find(string id) => _byId.TryGetValue(id, out var c) ? c : null;

    private static L1011ControlMap LoadEmbedded()
    {
        try
        {
            var asm = Assembly.GetExecutingAssembly();
            var name = Array.Find(asm.GetManifestResourceNames(),
                n => n.EndsWith("l1011_control_map.json", StringComparison.OrdinalIgnoreCase));
            if (name == null)
            {
                Log.Error("L1011", "l1011_control_map.json embedded resource not found - the TriStar will have no controls.");
                return new L1011ControlMap();
            }
            using var stream = asm.GetManifestResourceStream(name);
            if (stream == null)
            {
                Log.Error("L1011", $"Could not open embedded resource {name} - the TriStar will have no controls.");
                return new L1011ControlMap();
            }
            using var reader = new StreamReader(stream);
            var map = Parse(reader.ReadToEnd());
            Log.Info("L1011", $"Control map loaded: {map.Controls.Count} controls, {map.Breakers.Count} breakers, package {map.PackageVersion}.");
            return map;
        }
        catch (Exception ex)
        {
            Log.Error("L1011", $"Failed to load l1011_control_map.json: {ex.Message} - the TriStar will have no controls.");
            return new L1011ControlMap();
        }
    }
}

/// <summary>The control kinds the generator emits.</summary>
public static class L1011Kinds
{
    /// <summary>Positions, each reached with an absolute list of writes and events.</summary>
    public const string Switch = "switch";
    /// <summary>A momentary button: press, hold, release.</summary>
    public const string Button = "button";
    /// <summary>A button the aircraft resets itself: press only.</summary>
    public const string Latch = "latch";
    /// <summary>A switch that springs back to <see cref="L1011Control.Rest"/>.</summary>
    public const string Spring = "spring";
    /// <summary>A potentiometer: any value inside <see cref="L1011Control.Range"/>.</summary>
    public const string Knob = "knob";
    /// <summary>A knob that only steps up or down.</summary>
    public const string Encoder = "encoder";
    /// <summary>Nothing the map can replay.</summary>
    public const string None = "none";
}

/// <summary>One clickable cockpit control.</summary>
public sealed class L1011Control
{
    /// <summary>The model node id, e.g. <c>TOGGLE_BATTERY</c>. Also the MSFSBA variable key.</summary>
    [JsonPropertyName("id")] public string Id { get; set; } = string.Empty;
    [JsonPropertyName("file")] public string File { get; set; } = string.Empty;
    [JsonPropertyName("area")] public string Area { get; set; } = string.Empty;
    [JsonPropertyName("panel")] public string Panel { get; set; } = string.Empty;
    /// <summary>iniBuilds' tooltip title, e.g. "BATTERY SWITCH" (often shared by a family).</summary>
    [JsonPropertyName("title")] public string Title { get; set; } = string.Empty;
    [JsonPropertyName("kind")] public string Kind { get; set; } = L1011Kinds.None;
    /// <summary><c>L:NAME</c> or <c>A:NAME</c> holding the position; null for buttons and encoders.</summary>
    [JsonPropertyName("state_var")] public string? StateVar { get; set; }
    /// <summary>The unit the aircraft reads an A: state variable in (e.g. "Bool").</summary>
    [JsonPropertyName("state_unit")] public string? StateUnit { get; set; }
    /// <summary>Position value (as text) → iniBuilds' word for it; empty when the aircraft has none.</summary>
    [JsonPropertyName("positions")] public Dictionary<string, string> Positions { get; set; } = new();
    [JsonPropertyName("input_event")] public string? InputEvent { get; set; }
    /// <summary>Position value (as text) → the ordered effects that reach it.</summary>
    [JsonPropertyName("transitions")] public Dictionary<string, List<string>> Transitions { get; set; } = new();
    [JsonPropertyName("press")] public List<string> Press { get; set; } = new();
    [JsonPropertyName("release")] public List<string> Release { get; set; } = new();
    [JsonPropertyName("inc")] public List<string> Inc { get; set; } = new();
    [JsonPropertyName("dec")] public List<string> Dec { get; set; } = new();
    /// <summary>Knob effects with a <c>{v}</c> placeholder for the target value.</summary>
    [JsonPropertyName("set_template")] public List<string> SetTemplate { get; set; } = new();
    [JsonPropertyName("range")] public double[]? Range { get; set; }
    [JsonPropertyName("rest")] public double? Rest { get; set; }
    [JsonPropertyName("note")] public string? Note { get; set; }

    /// <summary>The positions in ascending value order with iniBuilds' words.</summary>
    public IReadOnlyList<(double Value, string Label)> OrderedPositions() =>
        Positions.Select(kv => (double.Parse(kv.Key, NumberStyles.Float, CultureInfo.InvariantCulture), kv.Value))
                 .OrderBy(p => p.Item1)
                 .ToList();

    /// <summary>The effects that reach <paramref name="value"/>, or null when it is not a position.</summary>
    public IReadOnlyList<string>? TransitionFor(double value) =>
        Transitions.TryGetValue(L1011Effect.FormatNumber(value), out var t) ? t : null;
}

/// <summary>One circuit breaker. Value 1 = pulled, 0 = pushed in.</summary>
public sealed class L1011Breaker
{
    [JsonPropertyName("index")] public int Index { get; set; }
    [JsonPropertyName("input_event")] public string InputEvent { get; set; } = string.Empty;
    /// <summary>iniBuilds' breaker name (644 of 981 have one), e.g. "HYD IND QTY".</summary>
    [JsonPropertyName("title")] public string Title { get; set; } = string.Empty;
    [JsonPropertyName("state_var")] public string? StateVar { get; set; }
    [JsonPropertyName("transitions")] public Dictionary<string, List<string>> Transitions { get; set; } = new();
}
